export const ErrorCode = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  MOCK_LOGIN_DISABLED: 'MOCK_LOGIN_DISABLED',
  MOCK_ACCOUNT_NOT_FOUND: 'MOCK_ACCOUNT_NOT_FOUND',
  WECHAT_LOGIN_NOT_CONFIGURED: 'WECHAT_LOGIN_NOT_CONFIGURED',
  FARM_NOT_FOUND: 'FARM_NOT_FOUND',
  PLOT_NOT_FOUND: 'PLOT_NOT_FOUND',
  DIAGNOSIS_NOT_FOUND: 'DIAGNOSIS_NOT_FOUND',
  DIAGNOSIS_EVIDENCE_REQUIRED: 'DIAGNOSIS_EVIDENCE_REQUIRED',
  DIAGNOSIS_INVALID_STATE: 'DIAGNOSIS_INVALID_STATE',
  DIAGNOSIS_IMAGE_BLURRY: 'DIAGNOSIS_IMAGE_BLURRY',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
